// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArR-2kt7zoHIKAdoKy35O5f_7mjelLpjg',
    appId: '1:371116792316:web:c0110db224bc3f2615ba79',
    messagingSenderId: '371116792316',
    projectId: 'imagetest-2c1f1',
    authDomain: 'imagetest-2c1f1.firebaseapp.com',
    storageBucket: 'imagetest-2c1f1.appspot.com',
    measurementId: 'G-6LYYJKSG2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4z9_Ill28UJGyxnzcrM2TX0IBcpijoXA',
    appId: '1:371116792316:android:48552677dc60f45415ba79',
    messagingSenderId: '371116792316',
    projectId: 'imagetest-2c1f1',
    storageBucket: 'imagetest-2c1f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0UMEv1rz0fNbKucJ-tBOvZ1ws3JsO6Hw',
    appId: '1:371116792316:ios:b74528dc0d9a909e15ba79',
    messagingSenderId: '371116792316',
    projectId: 'imagetest-2c1f1',
    storageBucket: 'imagetest-2c1f1.appspot.com',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0UMEv1rz0fNbKucJ-tBOvZ1ws3JsO6Hw',
    appId: '1:371116792316:ios:e3a082bf5d74038115ba79',
    messagingSenderId: '371116792316',
    projectId: 'imagetest-2c1f1',
    storageBucket: 'imagetest-2c1f1.appspot.com',
    iosBundleId: 'com.example.testFirebase.RunnerTests',
  );
}
